# Generated by Django 4.2.6 on 2023-11-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zodiacsign',
            new_name='Patient',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient_table',
        ),
    ]
